sudo: required

language:
  - cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5

compiler:
  - gcc

os:
  - linux

before_install:
  - pip install --user cpp-coveralls
  - apt-get update -qq

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
