sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      env: CC=gcc-5 CXX=g++-5
      addons: &gcc5
        apt:
          packages:
            - libstdc++-5-dev
            - gcc-5
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
      install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq g++-5
        - sudo apt-get install -y libgtest-dev
        - cd /usr/src/gtest
        - sudo cmake CMakeLists.txt
        - sudo make
        - sudo cp *.a /usr/lib
        - sudo ldconfig
        - cd /home/travis/build/Chris-Kruining/cpp98posix-framework

      - os: linux
        sudo: required
        env: CC=gcc-5 CXX=clang++-5
        install:
          - sudo apt-get update -qq
          - sudo apt-get install -qq g++-5
          - sudo apt-get install -y libgtest-dev
          - cd /usr/src/gtest
          - sudo cmake CMakeLists.txt
          - sudo make
          - sudo cp *.a /usr/lib
          - sudo ldconfig
          - cd /home/travis/build/Chris-Kruining/cpp98posix-framework

branches:
  only:
    - master
    - "/^v\\d+\\./"

notifications:
  email: false

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
