sudo: required
dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-5
      - g++-5
      - clang-3.6

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

branches:
  only:
    - master
    - "/^v\\d+\\./"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - sudo ldconfig
  - cd /home/travis/build/Chris-Kruining/cpp98posix-framework

script:
  - mkdir build
  - cd build
  - cmake .. && make
